version: '3'

services:
  webapp:
    build: .
    container_name: tv_movie_processor
    ports:
      - "5000:5000"
    volumes:
      - /home/user/docker/tv_movie_processor/src:/src
      - /mnt/nfs/media_path:/mnt/nfs/media
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # Authentication credentials
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - MEDIA_ROOT=/mnt/nfs/media
      # Database configuration (sqlite by default)
      - DB_TYPE=sqlite
      # Uncomment and modify these for MySQL/PostgreSQL
      # - DB_TYPE=mysql+pymysql
      # - DB_USERNAME=root
      # - DB_PASSWORD=password
      # - DB_HOST=db
      # - DB_PORT=3306
      # - DB_NAME=tv_movie_processor
      # Application settings
      - SECRET_KEY=YourSecretKey
      - DEBUG=false
    # Ensure the container has enough resources
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G